### ISSUE TITLE
journal error

### ISSUE THREAD

**Issue by kroman0** [openprocurement/openprocurement.integrations.edr#21]
```
2017-03-31 14:31:05,955 INFO  [openprocurement.integrations.edr.views.verify][DummyThread-1] Error on processing request "[{u'message': u'Need pass id or passport'}]"
Traceback (most recent call last):
  File "/home/devel/edr_integrations/eggs/ExtendedJournalHandler-0.0.1-py2.7.egg/ExtendedJournalHandler/__init__.py", line 32, in emit
    **extra)
  File "/usr/lib64/python2.7/site-packages/systemd/journal.py", line 446, in send
    args.extend(_make_line(key, val) for key, val in kwargs.items())
  File "/usr/lib64/python2.7/site-packages/systemd/journal.py", line 446, in <genexpr>
    args.extend(_make_line(key, val) for key, val in kwargs.items())
  File "/usr/lib64/python2.7/site-packages/systemd/journal.py", line 400, in _make_line
    return field + '=' + value
TypeError: cannot concatenate 'str' and 'list' objects
Logged from file utils.py, line 82
```
Всі параметри які пишуться в журнал мусять бути стрічковими.

**Comment by kroman0** [comment]
#24
